[tools]
bottom = "latest"
chezmoi = "2.60.1"
go = "latest"
neovim = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
bat = "latest"
jq = "latest"
lazygit = "latest"
yazi = "latest"
zoxide = "latest"
zellij = "latest"
age = "latest"
node = "20.18"
cheat = "latest"
dotnet = "latest"
kubectl = "latest"
k9s = "latest"

[settings]
experimental = true
